### ISSUE TITLE
MariaDB 10.11

### ISSUE THREAD

**Issue by prudloff-insite** [docksal/service-mariadb#22]
Are there plans to ship the new 10.11 LTS?

**Comment by lmakarov** [comment]
It's on the way. Need to resolve some CI issues to publish a release.

**Comment by mauriciopieper** [comment]
Hi @lmakarov, do you have an eta for this? Thank you very much!

**Comment by lmakarov** [comment]
Here you go - `docksal/mariadb:10.11-1.4` 

https://github.com/docksal/service-mariadb/releases/tag/v1.4.0
